AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda for sending Email to SES



Parameters:
  Name: 
    Type: String
    MinLength: 3
    MaxLength: 30
  Stage:
    Type: String
    MinLength: 3
    MaxLength: 30


Resources:
  LeadAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      Name: !Sub "${Name}-${Stage}-api"


  APIKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: 
        Fn::GetAtt: [LeadAPI, ApiId]
      Description: API Key for the lead api
      Expires: 360


  APISchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId:
        Fn::GetAtt: [LeadAPI, ApiId]
      DefintionS3Location: ../../src/graphql/schema.graphql

  LeadsTableDataSource:
    Type: AWS::AppSync::DataSource
    DependsOn:
      - LeadAPI
    Properties:
      ApiId:
        Fn::GetAtt: [LeadAPI, ApiId]
      Name: !Sub "${Name}-${Stage}-leadstable"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Sub "{{resolve:ssm:/applications/${Name}/${Stage}/role/dynamodb/arn:1}}"
      DynamoDBConfig:
        TableName: !Sub "{{resolve:ssm:/applications/${Name}/${Stage}/db/name/leadstable:1}}"
        AwsRegion:
          Ref: AWS::Region

  AddNewLead:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt: [LeadAPI, ApiId]
      TypeName: Mutation
      DataSourceName:
        Fn::GetAtt: [LeadsTableDataSource, Name] 
      FieldName: addNewLead
      Kind: UNIT
      RequestMappingTemplateS3Location: ../../src/graphql/resolver/addnewlead-request.txt
      ResponseMappingTemplateS3Location: ../../src/graphql/resolver/addnewlead-response.txt

Outputs:
  APIEndpoint:
    Value:
      Fn::GetAtt: [LeadAPI, GraphQLUrl]
  APIKey:
    Value:
      Fn::GetAtt: [APIKey, ApiKey]
