AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda for sending Email to SES



Parameters:
  Name: 
    Type: String
    MinLength: 3
    MaxLength: 30
  Stage:
    Type: String
    MinLength: 3
    MaxLength: 30


Resources:
  SendEmailToSES:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: ../../src/functions/send-to-ses/
      Runtime: python3.8
      MemorySize: 128
      Timeout: 5
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeStream
                - dynamodb:GetShardIterator
                - dynamodb:ListStreams
                - dynamodb:GetRecords
              Resource: !Sub "{{resolve:ssm:/applications/${Name}/${Stage}/db/arn/leadstablestream:1}}"
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !Sub "{{resolve:ssm:/applications/${Name}/${Stage}/db/arn/leadstablestream:1}}"
            BatchSize: 10
            StartingPosition: TRIM_HORIZON

