AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Leadform for datastack.de
Parameters:
  Name:
    Type: String
    MinLength: 3
    MaxLength: 30
    Default: dsleadform
  Stage:
    Type: String
    MinLength: 3
    MaxLength: 30
    Default: local
Resources:
  LeadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${Name}-${Stage}-leadform
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: ts
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: ts
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  SendEmailToSES:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: s3://cfn-artifacts-datastack-leadform/3f14d13e251b0c2d919699e3cf48a49c
      Runtime: python3.8
      MemorySize: 128
      Timeout: 5
      Policies:
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:DescribeStream
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          - dynamodb:GetRecords
          Resource:
          - Fn::GetAtt:
            - LeadsTable
            - StreamArn
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - ses:SendEmail
          Resource:
          - Fn::Sub: arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/*
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::GetAtt:
              - LeadsTable
              - StreamArn
            BatchSize: 10
            StartingPosition: TRIM_HORIZON
  HTTPResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: HTTPRestApi
      ParentId:
        Fn::GetAtt:
        - HTTPRestApi
        - RootResourceId
      PathPart: leads
  HTTPRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name:
        Fn::Sub: ${Stage}-${Name}-api
      Description: Products HTTP endpoint to put data in DynamoDB
  HTTPDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
    - HTTPMethod
    Properties:
      RestApiId:
        Ref: HTTPRestApi
      StageName:
        Fn::Sub: ${Stage}
  HTTPMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Credentials:
          Fn::GetAtt:
          - IAMRole
          - Arn
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:dynamodb:action/PutItem
        RequestTemplates:
          application/json:
            Fn::Sub: "{ \"TableName\": \"${LeadsTable}\", \"Item\": { \"id\": { \"\
              S\": \"$context.requestId\" }, \"ts\": { \"S\": \"$context.requestTime\"\
              }, \"firstName\": { \"S\": \"$input.path('$.firstName')\"}, \"email\"\
              : { \"S\": \"$input.path('$.email')\"}, \"windowLocation\": { \"S\"\
              : \"$input.path('$.windowLocation')\"}, \"form\": { \"S\": \"$input.path('$.form')\"\
              } } }"
        PassthroughBehavior: WHEN_NO_MATCH
        IntegrationResponses:
        - StatusCode: 200
      ResourceId:
        Ref: HTTPResource
      RestApiId:
        Ref: HTTPRestApi
      MethodResponses:
      - StatusCode: 200
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            - dynamodb:ListTables
            Resource:
              Fn::GetAtt:
              - LeadsTable
              - Arn
